enable-magisk-update = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "both"
build-mode = "both"
version = "latest"
included-patches = "'Permanent repeat' 'Permanent shuffle'"
