enable-magisk-update = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "both"
build-mode = "both"
version = "latest"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
